from __future__ import unicode_literals

from django.db import models

# Create your models here.
class SAOW1(models.Model):
	roomid = models.CharField(max_length=20)
	timeOfDay = models.IntegerField()
	building = models.IntegerField()
	oneIsAVL = models.BooleanField()
	twoIsAVL = models.BooleanField()
	threeIsAVL = models.BooleanField()
	fourIsAVL = models.BooleanField()
	fiveIsAVL = models.BooleanField()
class SAOW2(models.Model):
	roomid = models.CharField(max_length=20)
	timeOfDay = models.IntegerField()
	building = models.IntegerField()
	oneIsAVL = models.BooleanField()
	twoIsAVL = models.BooleanField()
	threeIsAVL = models.BooleanField()
	fourIsAVL = models.BooleanField()
	fiveIsAVL = models.BooleanField()
class SAOW3(models.Model):
	roomid = models.CharField(max_length=20)
	timeOfDay = models.IntegerField()
	building = models.IntegerField()
	oneIsAVL = models.BooleanField()
	twoIsAVL = models.BooleanField()
	threeIsAVL = models.BooleanField()
	fourIsAVL = models.BooleanField()
	fiveIsAVL = models.BooleanField()
class SAOW4(models.Model):
	roomid = models.CharField(max_length=20)
	timeOfDay = models.IntegerField()
	building = models.IntegerField()
	oneIsAVL = models.BooleanField()
	twoIsAVL = models.BooleanField()
	threeIsAVL = models.BooleanField()
	fourIsAVL = models.BooleanField()
	fiveIsAVL = models.BooleanField()
class SAOW5(models.Model):
	roomid = models.CharField(max_length=20)
	timeOfDay = models.IntegerField()
	building = models.IntegerField()
	oneIsAVL = models.BooleanField()
	twoIsAVL = models.BooleanField()
	threeIsAVL = models.BooleanField()
	fourIsAVL = models.BooleanField()
	fiveIsAVL = models.BooleanField()
class SAOW6(models.Model):
	roomid = models.CharField(max_length=20)
	timeOfDay = models.IntegerField()
	building = models.IntegerField()
	oneIsAVL = models.BooleanField()
	twoIsAVL = models.BooleanField()
	threeIsAVL = models.BooleanField()
	fourIsAVL = models.BooleanField()
	fiveIsAVL = models.BooleanField()
class SAOW7(models.Model):
	roomid = models.CharField(max_length=20)
	timeOfDay = models.IntegerField()
	building = models.IntegerField()
	oneIsAVL = models.BooleanField()
	twoIsAVL = models.BooleanField()
	threeIsAVL = models.BooleanField()
	fourIsAVL = models.BooleanField()
	fiveIsAVL = models.BooleanField()
class SAOW8(models.Model):
	roomid = models.CharField(max_length=20)
	timeOfDay = models.IntegerField()
	building = models.IntegerField()
	oneIsAVL = models.BooleanField()
	twoIsAVL = models.BooleanField()
	threeIsAVL = models.BooleanField()
	fourIsAVL = models.BooleanField()
	fiveIsAVL = models.BooleanField()
class SAOW9(models.Model):
	roomid = models.CharField(max_length=20)
	timeOfDay = models.IntegerField()
	building = models.IntegerField()
	oneIsAVL = models.BooleanField()
	twoIsAVL = models.BooleanField()
	threeIsAVL = models.BooleanField()
	fourIsAVL = models.BooleanField()
	fiveIsAVL = models.BooleanField()
class SAOW10(models.Model):
	roomid = models.CharField(max_length=20)
	timeOfDay = models.IntegerField()
	building = models.IntegerField()
	oneIsAVL = models.BooleanField()
	twoIsAVL = models.BooleanField()
	threeIsAVL = models.BooleanField()
	fourIsAVL = models.BooleanField()
	fiveIsAVL = models.BooleanField()
class SAOW11(models.Model):
	roomid = models.CharField(max_length=20)
	timeOfDay = models.IntegerField()
	building = models.IntegerField()
	oneIsAVL = models.BooleanField()
	twoIsAVL = models.BooleanField()
	threeIsAVL = models.BooleanField()
	fourIsAVL = models.BooleanField()
	fiveIsAVL = models.BooleanField()
class SAOW12(models.Model):
	roomid = models.CharField(max_length=20)
	timeOfDay = models.IntegerField()
	building = models.IntegerField()
	oneIsAVL = models.BooleanField()
	twoIsAVL = models.BooleanField()
	threeIsAVL = models.BooleanField()
	fourIsAVL = models.BooleanField()
	fiveIsAVL = models.BooleanField()
class SAOW13(models.Model):
	roomid = models.CharField(max_length=20)
	timeOfDay = models.IntegerField()
	building = models.IntegerField()
	oneIsAVL = models.BooleanField()
	twoIsAVL = models.BooleanField()
	threeIsAVL = models.BooleanField()
	fourIsAVL = models.BooleanField()
	fiveIsAVL = models.BooleanField()
class SAOW14(models.Model):
	roomid = models.CharField(max_length=20)
	timeOfDay = models.IntegerField()
	building = models.IntegerField()
	oneIsAVL = models.BooleanField()
	twoIsAVL = models.BooleanField()
	threeIsAVL = models.BooleanField()
	fourIsAVL = models.BooleanField()
	fiveIsAVL = models.BooleanField()
class SAOW15(models.Model):
	roomid = models.CharField(max_length=20)
	timeOfDay = models.IntegerField()
	building = models.IntegerField()
	oneIsAVL = models.BooleanField()
	twoIsAVL = models.BooleanField()
	threeIsAVL = models.BooleanField()
	fourIsAVL = models.BooleanField()
	fiveIsAVL = models.BooleanField()
class SAOW16(models.Model):
	roomid = models.CharField(max_length=20)
	timeOfDay = models.IntegerField()
	building = models.IntegerField()
	oneIsAVL = models.BooleanField()
	twoIsAVL = models.BooleanField()
	threeIsAVL = models.BooleanField()
	fourIsAVL = models.BooleanField()
	fiveIsAVL = models.BooleanField()
class SAOW17(models.Model):
	roomid = models.CharField(max_length=20)
	timeOfDay = models.IntegerField()
	building = models.IntegerField()
	oneIsAVL = models.BooleanField()
	twoIsAVL = models.BooleanField()
	threeIsAVL = models.BooleanField()
	fourIsAVL = models.BooleanField()
	fiveIsAVL = models.BooleanField()
class SAOW18(models.Model):
	roomid = models.CharField(max_length=20)
	timeOfDay = models.IntegerField()
	building = models.IntegerField()
	oneIsAVL = models.BooleanField()
	twoIsAVL = models.BooleanField()
	threeIsAVL = models.BooleanField()
	fourIsAVL = models.BooleanField()
	fiveIsAVL = models.BooleanField()
class SAOW19(models.Model):
	roomid = models.CharField(max_length=20)
	timeOfDay = models.IntegerField()
	building = models.IntegerField()
	oneIsAVL = models.BooleanField()
	twoIsAVL = models.BooleanField()
	threeIsAVL = models.BooleanField()
	fourIsAVL = models.BooleanField()
	fiveIsAVL = models.BooleanField()
class SAOW20(models.Model):
	roomid = models.CharField(max_length=20)
	timeOfDay = models.IntegerField()
	building = models.IntegerField()
	oneIsAVL = models.BooleanField()
	twoIsAVL = models.BooleanField()
	threeIsAVL = models.BooleanField()
	fourIsAVL = models.BooleanField()
	fiveIsAVL = models.BooleanField()
class SAOW21(models.Model):
	roomid = models.CharField(max_length=20)
	timeOfDay = models.IntegerField()
	building = models.IntegerField()
	oneIsAVL = models.BooleanField()
	twoIsAVL = models.BooleanField()
	threeIsAVL = models.BooleanField()
	fourIsAVL = models.BooleanField()
	fiveIsAVL = models.BooleanField()