# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_saow1_saow10_saow11_saow12_saow13_saow14_saow15_saow16_saow17_saow18_saow19_saow2_saow20_saow21_saow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saow1',
            old_name='thereIsAVL',
            new_name='threeIsAVL',
        ),
        migrations.RenameField(
            model_name='saow10',
            old_name='thereIsAVL',
            new_name='threeIsAVL',
        ),
        migrations.RenameField(
            model_name='saow11',
            old_name='thereIsAVL',
            new_name='threeIsAVL',
        ),
        migrations.RenameField(
            model_name='saow12',
            old_name='thereIsAVL',
            new_name='threeIsAVL',
        ),
        migrations.RenameField(
            model_name='saow13',
            old_name='thereIsAVL',
            new_name='threeIsAVL',
        ),
        migrations.RenameField(
            model_name='saow14',
            old_name='thereIsAVL',
            new_name='threeIsAVL',
        ),
        migrations.RenameField(
            model_name='saow15',
            old_name='thereIsAVL',
            new_name='threeIsAVL',
        ),
        migrations.RenameField(
            model_name='saow16',
            old_name='thereIsAVL',
            new_name='threeIsAVL',
        ),
        migrations.RenameField(
            model_name='saow17',
            old_name='thereIsAVL',
            new_name='threeIsAVL',
        ),
        migrations.RenameField(
            model_name='saow18',
            old_name='thereIsAVL',
            new_name='threeIsAVL',
        ),
        migrations.RenameField(
            model_name='saow19',
            old_name='thereIsAVL',
            new_name='threeIsAVL',
        ),
        migrations.RenameField(
            model_name='saow2',
            old_name='thereIsAVL',
            new_name='threeIsAVL',
        ),
        migrations.RenameField(
            model_name='saow20',
            old_name='thereIsAVL',
            new_name='threeIsAVL',
        ),
        migrations.RenameField(
            model_name='saow21',
            old_name='thereIsAVL',
            new_name='threeIsAVL',
        ),
        migrations.RenameField(
            model_name='saow3',
            old_name='thereIsAVL',
            new_name='threeIsAVL',
        ),
        migrations.RenameField(
            model_name='saow4',
            old_name='thereIsAVL',
            new_name='threeIsAVL',
        ),
        migrations.RenameField(
            model_name='saow5',
            old_name='thereIsAVL',
            new_name='threeIsAVL',
        ),
        migrations.RenameField(
            model_name='saow6',
            old_name='thereIsAVL',
            new_name='threeIsAVL',
        ),
        migrations.RenameField(
            model_name='saow7',
            old_name='thereIsAVL',
            new_name='threeIsAVL',
        ),
        migrations.RenameField(
            model_name='saow8',
            old_name='thereIsAVL',
            new_name='threeIsAVL',
        ),
        migrations.RenameField(
            model_name='saow9',
            old_name='thereIsAVL',
            new_name='threeIsAVL',
        ),
    ]
