# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20160829_1235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SAOW1',
        ),
        migrations.DeleteModel(
            name='SAOW10',
        ),
        migrations.DeleteModel(
            name='SAOW11',
        ),
        migrations.DeleteModel(
            name='SAOW12',
        ),
        migrations.DeleteModel(
            name='SAOW13',
        ),
        migrations.DeleteModel(
            name='SAOW14',
        ),
        migrations.DeleteModel(
            name='SAOW15',
        ),
        migrations.DeleteModel(
            name='SAOW16',
        ),
        migrations.DeleteModel(
            name='SAOW17',
        ),
        migrations.DeleteModel(
            name='SAOW18',
        ),
        migrations.DeleteModel(
            name='SAOW19',
        ),
        migrations.DeleteModel(
            name='SAOW2',
        ),
        migrations.DeleteModel(
            name='SAOW20',
        ),
        migrations.DeleteModel(
            name='SAOW21',
        ),
        migrations.DeleteModel(
            name='SAOW3',
        ),
        migrations.DeleteModel(
            name='SAOW4',
        ),
        migrations.DeleteModel(
            name='SAOW5',
        ),
        migrations.DeleteModel(
            name='SAOW6',
        ),
        migrations.DeleteModel(
            name='SAOW7',
        ),
        migrations.DeleteModel(
            name='SAOW8',
        ),
        migrations.DeleteModel(
            name='SAOW9',
        ),
    ]
